### ISSUE TITLE
pip install swagger-tester failed at requests ~=2.11

### ISSUE THREAD

**Issue by blankdots** [Trax-air/swagger-tester#41]
Kinda failed to install swagger-tester both from source and from pip
```
Downloading/unpacking swagger-tester
  Downloading swagger_tester-0.2.7-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2421, in _dep_map
    return self.__dep_map
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2283, in __getattr__
    raise AttributeError(attr)
AttributeError: _DistInfoDistribution__dep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/req.py", line 1265, in prepare_files
    req_to_install.extras):
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2232, in requires
    dm = self._dep_map
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2423, in _dep_map
    self.__dep_map = self._compute_dependencies()
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2447, in _compute_dependencies
    parsed = next(parse_requirements(distvers))
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2544, in parse_requirements
    line, p, specs = scan_list(VERSION,LINE_END,line,p,(1,2),"version spec")
  File "/home/user/dev/test/lib/python3.4/site-packages/pip/_vendor/pkg_resources.py", line 2512, in scan_list
    raise ValueError("Expected "+item_name+" in",line,"at",line[p:])
ValueError: ('Expected version spec in', 'requests ~=2.11', 'at', ' ~=2.11')

Storing debug log for failure in /home/user/.pip/pip.log

```

Setup details: Ubuntu 14.04 and yes I did have previously install `requests` (2.12.3) also tested in virtualenv (can provide the full pip freeze on request)

Managed however to install from source by changing in the `requirements.txt` the line `requests ~=2.11` to `requests >= 2.11`.

**Comment by cyprieng** [comment]
Can you update pip and retry to install swagger-tester ?

**Comment by blankdots** [comment]
fixed. thx.
